### ISSUE TITLE
use multi dimensional array..

### ISSUE THREAD

**Issue by Amitminer** [Amitminer/CustomItem#3]
Currently, I'm using libCoolDown, which essentially uses a single array. However, it breaks my entire code. I mean, when you use a freezing sword and then try a lightning sword, you will encounter an error. I will fix it as soon as possible. (For now, I'm on a break.) I'll address it within the next month

**Comment by justauser001** [comment]
Ok

**Comment by Amitminer** [comment]
okay .. [Fixed](https://github.com/Amitminer/CustomItem/commit/88c70f4df8e973f62673fb635ea71b4b6ecbd209)
