### ISSUE TITLE
Crashing when taking lighting sword

### ISSUE THREAD

**Issue by justauser001** [Amitminer/CustomItem#4]
Crashing when I do /customitems and choose lighting sword

**Comment by Amitminer** [comment]
crash log pls?

**Comment by justauser001** [comment]
THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: CustomItem

Thread: Main
Error: An error occurred while adding an enchantment to the item.
File: plugins/CustomItem-dev/src/Manager/ItemManager
Line: 74
Type: InvalidArgumentException
Backtrace:
#0 plugins/CustomItem-dev/src/Manager/CustomItemsManag

**Comment by Amitminer** [comment]
thanks for reporting!.. I'll resolved it soon..

**Comment by Amitminer** [comment]
fixed... [Commit](https://github.com/Amitminer/CustomItem/commit/e23c0fcd37459be95b559e4e1f699c0966d42167)
